version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev_secret_key_change_in_production
      - ADMIN_KEY=rAwwIzAd-RGz8eYGo_6ymz8Wd4EFEnBC6R--MWQ8gK8
      - PORT=5000
      - HOST=0.0.0.0
      - FLASK_ENV=development
      - DEBUG=True
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - AUTHORIZED_SERVER_ID=${AUTHORIZED_SERVER_ID}
      - BACKEND_URL=http://backend:5000
      - ADMIN_KEY=rAwwIzAd-RGz8eYGo_6ymz8Wd4EFEnBC6R--MWQ8gK8
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./discord-bot:/app

volumes:
  backend_data: 