[start]
cmd = "cd backend && python app.py"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && pip install -r requirements.txt"]

[variables]
PORT = "5000"
FLASK_ENV = "production" 