[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "python run.py"

[variables]
PORT = "5000"
FLASK_ENV = "production" 