[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile - app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "5000"
HOST = "0.0.0.0"
FLASK_ENV = "production" 